### ISSUE TITLE
Possible error with two-word model

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/StructureManager#23]
This is  a **bug | feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Every time I try to generate a structure with a model composed of two words I receive problems of routes when edit and show.
![captura de pantalla de 2019-02-12 22-47-14](https://user-images.githubusercontent.com/12703614/52685818-28666d80-2f19-11e9-8ec4-c801fa1fb674.png)
The table and the create form work perfectly
![captura de pantalla de 2019-02-12 22-55-53](https://user-images.githubusercontent.com/12703614/52685913-88f5aa80-2f19-11e9-96af-447b886a5698.png)
The name of my model is TransferProduct 

### Steps to Reproduce

Creating a new structure for users_pos for example in my model convention would have a name UserPos

Pd. I apologize in advance if I'm not using the correct naming convention and that's why the error occurs.
I would like a little guidance in case, thank you.

**Comment by aocneanu** [comment]
If you want to use the default (dynamic) buttons in datatable, the convention is that the model should be the singular of the last segment of your route prefix, as defined in the template:

if you have  `"routePrefix": "someRouteGroup.someSubGroup.threeWordModels"` then the model should be `ThreeWordModel`, not something else. If you want to use custom naming then you will have to define your own actions in the template instead of using the defaults.

A quick mention / recommendation, in 2+ years of using this lib in our apps we have never had a reason not to use the dynamic buttons. Having everything matched between FE and BE in terms of routes, groups, model names and so on only means less complexity and easier to manage apps. So just name your route `inventory.transferProducts.show`

**Comment by heyner29** [comment]
Thank you. I solved it as you suggested, having all the routes with `transferProducts`, and I'll keep it in mind for next.
