### ISSUE TITLE
Last update broke Model creation?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#5]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Last update seems to have broken model creation:
```bash
In ClassLoader.php line 444:

  include(C:\Path\To\Project\vendor\composer/../../app/ModelName.php): failed to open st
  ream: No such file or directory
```

### Steps to Reproduce

1. Generate structure using `enso:make:structure`, note an error opening the model file on generate

### Expected behavior

structure to become generated

### Actual behavior

![image](https://user-images.githubusercontent.com/932193/44465011-9db54d80-a61c-11e8-8ed7-8387cda26915.png)

**Comment by aocneanu** [comment]
try a `composer dump-autoload`  and report back :)

**Comment by aocneanu** [comment]
Nope, because it has nothing to do with Enso, it’s a Laravel thing. When you create a Mode with artisan the autoloader is update too. If then you delete the model and try recreatig it you will hit the above problem.

I’m seeing that you enjoy the support you’re getting... Enso could use your support as well. You may star the packages that you like in Enso at anytime ;)

**Comment by aocneanu** [comment]
Will fix it tomorrow.

**Comment by jlsjonas** [comment]
Looks like you commented just as my pull request was propagating :)

**Comment by aocneanu** [comment]
True:)
